### ISSUE TITLE
wechaty-getting-started test

### ISSUE THREAD

**Issue by lijiarui** [wechaty/wechaty-puppet-padplus#12]
## basic

- [ ] contact-bot
  - [x] Get right contact number
  - [ ] Get Official account #19
  - [x] Get personal account 
  - [x] Save contact avatar (MAX=17)
- [ ] ding-dong-bot, send `ding|ping|bing|code`
  - [x]  reply `dong`
  - [x]  reply image
  - [ ] check send image sequence

## advanced

- [ ] demo-in-tutorial
  - [ ] Receive friend request automatically
  - [ ] Confirm friend request and reply `Nice to meet you`
  - [x] Get room topic  & message in console #14
  - [x] Get contact message in console
  - [x] say `Hello` reply a string
  - [ ] say `room` will invite you to room `wechaty test room` and say weclome in the room #15
  - [ ] say `fword` will remove you from `wechaty test room` and say unwelcome in the room
- [ ] friend-bot
  - [ ] Get Friendship event, fileHelper say logMessage
  - [ ] If Friendship request is `ding`, receive automatically, and say hello
  - [ ] If accept the friendship, send logMessage to fileHelper
- [ ] media-file-bot #13 
  - [ ] If receive media message, save to local
  - [ ] image
  - [ ] voice
  - [ ] attachment
  - [ ] vedio
- [ ] room-bot
  - [ ] room-join: say hello to the new comer
  - [ ] room-leave: say goodbye to the leaver
  - [ ] room-topic: say who change the oldTopic to newTopic
  - [ ] if you say `dong` in a room, bot will quit the room
  - [ ] If you say `dong` peer to peer, just common reply
  - [ ] If you say `ding` in a room, bot will remove you from the room
  - [ ] If you say `ding` peer to peer and there is no room begin with `ding`, will create a dingRoom.
  - [ ] If you say `ding` peer to peer && there is a room begin with `ding` && you are in dingRoom, dingRoom say and bot reply you.
  - [ ] If you say `ding` peer to peer && there is a room begin with `ding` && you are not in dingRoom. bot will invite you in dingRoom,  reply to you and welcome you in the room
  - [ ] If dingRoom inviter isn't the bot, bot will warn in the room and change the topic to `ding - warn - inviter.name()`
- [ ] self-testing-bot
  - TODO

**Comment by su-chang** [comment]
Long time no update about this issue, it will be closed now.
